name: "boilerplate"
version: "0.0.1"

# profile needs to be in  ~/.dbt/profiles.yml file
profile: "boilerplate"

data-paths: ["data"]
macro-paths: ["macros"]
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
log-path: "logs"

models:
  boilerplate:
    vars:
      "timezone": "UTC"

seeds:
  boilerplate:
    enabled: true
    schema: raw
    country:
      # Override column types
      column_types:
        country_code: varchar(2)
        country_name: varchar(50)
        google_criteria_id: integer
        currency_code: varchar(3)
        currency_name: varchar(50)
        is_gdpr_country: boolean